re-import data at start of plotting
swcarpentry/python-novice-inflammation pull request #986
Opened 2022-04-01 17:38 UTC by brownsarahm

This makes the individual episodes a little more self-containted and makes it easier for instructors who may swap out between episdoes.  

It also will mean that we do not need to dis-allow this episode for teaching demos [see PR](https://github.com/carpentries/instructor-training/pull/1346/commits/5ecd1baf934afa0a386c74ee82e29027f7ed8d0c)

2022-04-01 19:22 UTC, ldko commented
Note, this overlaps with #893 and #876. I think it would be good to get some sort of fix out for this as it clearly has come up for multiple people, but I am no longer a maintainer here. ping @maxim-belkin

2022-04-04 16:38 UTC, maxim-belkin commented
Making episodes more self-contained is a good thing, so I'm +1 here. Following my comment from 2020 (https://github.com/swcarpentry/python-novice-inflammation/pull/876#issuecomment-706258785), I would suggest two things:
1. Put this in a prereq (or callout) box at the beginning of the episode.
2. Provide a brief explanation on when the proposed steps (importing numpy + loading data) are necessary.

2022-04-04 18:05 UTC, brownsarahm commented
@maxim-belkin does that meet your request?

2022-04-04 18:16 UTC, maxim-belkin requested changes
Thanks, @brownsarahm. Looks good! A few minor fixes and it will be good to go.
I also wonder if this note should be a `.prereq` instead of a `.callout` -- in that case we could standardize the title to "Episode prerequisites" and later use this title in other episodes (if and when necessary).

2022-04-04 18:16 UTC, maxim-belkin commented on _episodes/03-matplotlib.md
> +> notebook at this point you need the following two lines.
```suggestion
> notebook at this point, you need the following two lines:
```

2022-04-04 18:16 UTC, maxim-belkin commented on _episodes/03-matplotlib.md
> +> {: .source}
```suggestion
> {: .language-python}
```

2022-04-04 18:20 UTC, brownsarahm commented
I do like episode prereqs. Espeically if we can promote that as a broader trend across lesson. Will change.

2022-04-04 18:44 UTC, maxim-belkin approved these changes
Thank you so much for this contribution, Sarah! Looks great!

2022-04-04 18:46 UTC, merged